[package]
name = "controller"
version = "0.1.0"
edition = "2024"

[dependencies]
enigo = "0.5.0"
hidapi = "2.6.3"

[patch.crates-io]
enigo = { git = "https://github.com/LeeeSe/enigo", branch = "patch-1" }
