# Xbox手柄控制器配置文件示例
# 复制此文件为 config.toml 并根据需要修改设置

# === 基本阈值设置 ===

# 模拟扳机阈值 (0-255)
# 当LT扳机按下超过此值时激活陀螺仪控制
analog_trigger_threshold = 20

# 左摇杆死区 (0-32767)
# 摇杆在此范围内的微小移动将被忽略
joystick_deadzone = 1000

# 右摇杆死区 (0-32767)
# 右摇杆在此范围内的移动将被忽略（用于滚动）
right_joystick_deadzone = 5000

# 陀螺仪死区 (0-32767)
# 陀螺仪在此范围内的微小变化将被忽略
gyro_deadzone = 10

# 页面导航触发阈值 (0-32767)
# 右摇杆左右移动超过此值时触发前进/后退
nav_trigger_threshold = 32001

# === 灵敏度设置 ===

# 左摇杆灵敏度 (推荐范围: 5.0-30.0)
# 数值越大，鼠标移动越快
joystick_sensitivity = 15.0

# 陀螺仪灵敏度 (推荐范围: 0.01-0.2)
# 数值越大，陀螺仪控制越敏感
gyro_sensitivity = 0.08

# 直接滚动灵敏度 (推荐范围: 5.0-50.0)
# 数值越大，滚动速度越快
direct_scroll_sensitivity = 20.0

# === 高级设置 ===

# 主导轴系数 (必须大于1.0)
# 用于区分摇杆的主要移动方向
# 数值越大，越容易区分垂直/水平移动
dominant_axis_factor = 1.5

# 步调器循环频率 (Hz, 推荐范围: 30-120)
# 控制滚动的平滑程度，数值越高越平滑但CPU占用更高
pacer_loop_hz = 75

# === 按钮映射配置示例 ===
# 注意：以下是按钮映射的格式示例，实际配置在代码中定义

# [button_mapping]
# button_a = "LeftClick"              # A键 - 左鼠标点击
# button_b = "RightClick"             # B键 - 右鼠标点击
# button_x = "CloseWindow"            # X键 - 关闭窗口 (Cmd+W)
# button_y = "MissionControl"         # Y键 - 调度中心
# button_lb = "PrevTab"               # LB键 - 上一个标签页
# button_rb = "NextTab"               # RB键 - 下一个标签页

# === 新增：方向键映射 ===
# dpad_up = "Refresh"                 # 上方向键 - 刷新页面 (Cmd+R)
# dpad_down = "None"                  # 下方向键 - 无操作
# dpad_left = "None"                  # 左方向键 - 无操作
# dpad_right = "NewTab"               # 右方向键 - 新建标签页 (Cmd+T)

# === 新增：组合键映射 ===
# lt_x_combo = "QuitApp"              # LT + X组合键 - 退出应用程序 (Cmd+Q)

# 自定义快捷键示例：
# button_x = { CustomShortcut = { modifiers = ["cmd", "shift"], key = "t" } }

# === 按键功能说明 ===

# 基础按钮动作：
# - "LeftClick"        : 鼠标左键点击
# - "RightClick"       : 鼠标右键点击
# - "CloseWindow"      : 关闭窗口 (Cmd+W)
# - "MissionControl"   : 调度中心
# - "PrevTab"          : 上一个标签页 (Cmd+Shift+[)
# - "NextTab"          : 下一个标签页 (Cmd+Shift+])

# 新增按钮动作：
# - "QuitApp"          : 退出应用程序 (Cmd+Q)
# - "NewTab"           : 新建标签页 (Cmd+T)
# - "Refresh"          : 刷新页面 (Cmd+R)
# - "None"             : 无操作

# 组合键说明：
# - LT + X 同时按下时触发 lt_x_combo 动作
# - 当LT按下时，单独按X键不会触发 button_x 动作
# - 方向键可以独立配置不同的功能

# === 配置说明 ===

# 1. 死区设置：
#    - 如果发现摇杆有轻微漂移，可以增加对应的死区值
#    - 如果摇杆响应不够灵敏，可以减少死区值

# 2. 灵敏度调整：
#    - 鼠标移动太快：减少 joystick_sensitivity 或 gyro_sensitivity
#    - 鼠标移动太慢：增加对应的灵敏度值
#    - 滚动太快/太慢：调整 direct_scroll_sensitivity

# 3. 性能优化：
#    - 如果CPU占用过高：减少 pacer_loop_hz
#    - 如果滚动不够平滑：增加 pacer_loop_hz

# 4. 手柄校准：
#    - 如果手柄按钮映射不正确，请检查手柄是否为Xbox兼容型号
#    - 支持的VID/PID: 0x045E:0x028E (Xbox 360 Controller)

# === 故障排除 ===

# 问题：鼠标移动不平滑
# 解决：减少死区值，增加灵敏度

# 问题：意外触发导航
# 解决：增加 nav_trigger_threshold 值

# 问题：陀螺仪过于敏感
# 解决：增加 gyro_deadzone，减少 gyro_sensitivity

# 问题：滚动卡顿
# 解决：增加 pacer_loop_hz 值

# === 重连配置 ===

[reconnection]
# 是否启用自动重连 (true/false)
# 当手柄断开连接时，程序是否自动等待并尝试重新连接
enable_auto_reconnect = true

# 重连尝试间隔 (毫秒)
# 每次重连尝试之间的等待时间
reconnect_interval_ms = 2000

# 最大重连尝试次数 (0表示无限制)
# 超过此次数后停止重连尝试，0表示永不停止
max_reconnect_attempts = 0

# 是否显示重连消息 (true/false)
# 控制是否在控制台显示重连状态信息
show_reconnect_messages = true

# 最大静默失败次数
# 超过此次数的连续失败后开始显示重连消息
# 用于减少控制台输出的频率
max_silent_failures = 5

# === 重连配置说明 ===

# 1. 自动重连功能：
#    - 当手柄休眠或断开连接时，程序不会退出
#    - 程序会定期尝试重新连接手柄
#    - 手柄重新连接后可以立即继续使用

# 2. 重连策略：
#    - enable_auto_reconnect = false：禁用自动重连，断开后程序退出
#    - max_reconnect_attempts = 0：无限重连，永不放弃
#    - max_reconnect_attempts > 0：达到次数后停止重连

# 3. 消息控制：
#    - show_reconnect_messages = false：静默重连，不显示任何消息
#    - max_silent_failures：控制消息显示频率，避免刷屏

# 4. 使用建议：
#    - 观看视频时：建议启用自动重连，设置较长的重连间隔
#    - 游戏使用时：可以设置较短的重连间隔以快速恢复
#    - 电池管理：手柄休眠是正常的节电行为，无需担心

# === 重连故障排除 ===

# 问题：手柄断开后程序立即退出
# 解决：检查 enable_auto_reconnect 是否为 true

# 问题：重连消息太频繁
# 解决：增加 max_silent_failures 或设置 show_reconnect_messages = false

# 问题：重连尝试太频繁影响系统性能
# 解决：增加 reconnect_interval_ms 的值

# 问题：重连失败次数过多想要停止
# 解决：设置合适的 max_reconnect_attempts 值
