# Xbox控制器配置文件示例
# 本文件展示了新的灵活按键绑定系统，包括右摇杆方向绑定

# 基本控制器参数
analog_trigger_threshold = 20
joystick_deadzone = 1000
right_joystick_deadzone = 5000
gyro_deadzone = 10
nav_trigger_threshold = 32001
dominant_axis_factor = 1.5
joystick_sensitivity = 15.0
gyro_sensitivity = 0.08
direct_scroll_sensitivity = 20.0
pacer_loop_hz = 75

# 重连配置
[reconnection]
enable_auto_reconnect = true
reconnect_interval_ms = 2000
max_reconnect_attempts = 0
show_reconnect_messages = true
max_silent_failures = 5

# 按键绑定配置 - 支持单独按键、组合键和右摇杆方向
[button_mappings]

# 单独按键绑定
"A" = "LeftClick"
"B" = "RightClick"
"X" = "CloseWindow"
"Y" = "MissionControl"
"LB" = "PrevTab"
"RB" = "NextTab"

# 方向键绑定
"DPad_Up" = "Refresh"
"DPad_Down" = "None"
"DPad_Left" = "None"
"DPad_Right" = "NewTab"

# 组合键绑定 - LT + 按键
"LT+X" = "QuitApp"
"LT+Y" = { CustomShortcut = { modifiers = ["cmd"], key = "1" } }
"LT+A" = { CustomShortcut = { modifiers = ["cmd", "shift"], key = "n" } }
"LT+B" = { CustomShortcut = { modifiers = ["cmd"], key = "w" } }

# 右摇杆方向绑定 - LT + 右摇杆方向
"LT+RStick_Up" = { CustomShortcut = { modifiers = ["cmd"], key = "up" } }      # Cmd + 上箭头
"LT+RStick_Down" = { CustomShortcut = { modifiers = ["cmd"], key = "down" } }    # Cmd + 下箭头
"LT+RStick_Left" = { CustomShortcut = { modifiers = ["cmd"], key = "left" } }    # Cmd + 左箭头
"LT+RStick_Right" = { CustomShortcut = { modifiers = ["cmd"], key = "right" } }  # Cmd + 右箭头

# 更多组合键示例
"LT+DPad_Up" = { CustomShortcut = { modifiers = ["cmd"], key = "plus" } }
"LT+DPad_Down" = { CustomShortcut = { modifiers = ["cmd"], key = "minus" } }
"LT+LB" = { CustomShortcut = { modifiers = ["cmd", "shift"], key = "left" } }
"LT+RB" = { CustomShortcut = { modifiers = ["cmd", "shift"], key = "right" } }